//! Persisted configuration: bindings for now; room to grow later.
use crate::input::Bindings;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::sync::Mutex;

const CONFIG_PATH: &str = "config.toml";
pub const MAX_USERNAME_LEN: usize = 24;

static SIGNALING_URL: Mutex<Option<String>> = Mutex::new(None);

pub fn set_signaling_url(url: String) {
    let trimmed = url.trim_end_matches('/').to_string();
    if let Ok(mut guard) = SIGNALING_URL.lock() {
        *guard = if trimmed.is_empty() {
            None
        } else {
            Some(trimmed)
        };
    }
}

pub fn signaling_url() -> Option<String> {
    if let Ok(guard) = SIGNALING_URL.lock() {
        if let Some(ref url) = *guard {
            if !url.is_empty() {
                return Some(url.clone());
            }
        }
    }
    None
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Config {
    #[serde(default)]
    pub bindings: Bindings,
    /// Public signaling/matchmaking service URL.
    #[serde(default)]
    pub signaling_url: String,
    /// Discord Rich Presence application ID.
    #[serde(default)]
    pub discord_client_id: String,
    /// Whether Discord Rich Presence should start when configured.
    #[serde(default = "default_true")]
    pub discord_rpc_enabled: bool,
    /// Public handle used for matchmaking, stats, and overlays.
    #[serde(default)]
    pub player_username: String,
    /// True after the matchmaking service has accepted this username once.
    #[serde(default)]
    pub player_username_confirmed: bool,
    /// True when `player_username` was filled by the Wu-name generator rather
    /// than typed/saved by the player.
    #[serde(default)]
    pub player_username_autogenerated: bool,
    /// Optional email used to make the guest stats identity portable.
    #[serde(default)]
    pub stats_email: String,
    /// Start in desktop fullscreen and keep that preference when toggled.
    #[serde(default)]
    pub fullscreen: bool,
    /// SDL renderer preference for local hardware rendering experiments.
    #[serde(default)]
    pub render_profile: RenderProfile,
    /// Audio output level as a percentage.
    #[serde(default = "default_volume_percent")]
    pub volume_percent: u8,
    /// Audio queue depth. Higher values tolerate frame jitter better.
    #[serde(default)]
    pub audio_buffer: AudioBuffer,
    /// Gameplay frame presentation filter.
    #[serde(default)]
    pub video_filter: VideoFilter,
    /// Enable rounded CRT glass/corner shading on CRT-style filters.
    #[serde(default = "default_true")]
    pub crt_corner_bend: bool,
    /// How the gameplay frame is fit into the window.
    #[serde(default)]
    pub aspect_mode: AspectMode,
    /// Which scorebar layout to draw over gameplay.
    #[serde(default)]
    pub scorebar_style: ScorebarStyle,
    /// Optional Discord webhook URL. When non-empty, Freeplay posts round/match
    /// results here during netplay sessions. Get one from any Discord channel
    /// via Edit Channel → Integrations → Webhooks → New Webhook → Copy URL.
    #[serde(default)]
    pub discord_webhook_url: String,
    /// Optional stats service URL for ghost uploads and leaderboards.
    #[serde(default)]
    pub stats_url: String,
    /// Stable installation identifier used to anchor a persistent guest-stats
    /// profile when no email is registered. Generated once on first run and
    /// never shown to the user. Sent to the server as `device_id` in
    /// `/auth/guest` requests so stats carry across sessions without email.
    #[serde(default)]
    pub guest_device_id: String,
    /// GGRS input delay in frames (default 3). Higher values trade input
    /// latency for fewer rollbacks on high-latency connections. The MK2
    /// ROM's +6-tick combo windows support up to 6 frames without missing
    /// specials. Valid range: 0–8.
    #[serde(default = "default_input_delay")]
    pub input_delay: u32,
}

impl Default for Config {
    fn default() -> Self {
        // Derived Default would zero every field, ignoring the serde defaults
        // (a fresh install used to start with volume_percent = 0, i.e. silent).
        // Deserializing an empty TOML applies the serde defaults, so a missing
        // config file behaves exactly like an empty one.
        toml::from_str("").expect("empty config deserializes via serde defaults")
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AudioBuffer {
    Low,
    Normal,
    #[default]
    Stable,
}

impl AudioBuffer {
    pub fn label(self) -> &'static str {
        match self {
            AudioBuffer::Low => "LOW",
            AudioBuffer::Normal => "NORMAL",
            AudioBuffer::Stable => "STABLE",
        }
    }

    pub fn ms(self) -> u32 {
        match self {
            AudioBuffer::Low => 120,
            AudioBuffer::Normal => 220,
            AudioBuffer::Stable => 320,
        }
    }

    pub fn cycle(self, delta: i8) -> Self {
        let all = [AudioBuffer::Low, AudioBuffer::Normal, AudioBuffer::Stable];
        let idx = all.iter().position(|v| *v == self).unwrap_or(2) as i8;
        let next = (idx + delta).rem_euclid(all.len() as i8) as usize;
        all[next]
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RenderProfile {
    #[default]
    Auto,
    Hardware,
    HardwareVsync,
    Software,
}

impl RenderProfile {
    pub fn label(self) -> &'static str {
        match self {
            RenderProfile::Auto => "AUTO",
            RenderProfile::Hardware => "HARDWARE",
            RenderProfile::HardwareVsync => "HW VSYNC",
            RenderProfile::Software => "SOFTWARE",
        }
    }

    pub fn cycle(self, delta: i8) -> Self {
        let all = [
            RenderProfile::Auto,
            RenderProfile::Hardware,
            RenderProfile::HardwareVsync,
            RenderProfile::Software,
        ];
        let idx = all.iter().position(|v| *v == self).unwrap_or(0) as i8;
        let next = (idx + delta).rem_euclid(all.len() as i8) as usize;
        all[next]
    }

    pub fn wants_acceleration(self) -> bool {
        matches!(self, RenderProfile::Hardware | RenderProfile::HardwareVsync)
    }

    pub fn wants_software(self) -> bool {
        matches!(self, RenderProfile::Software)
    }

    pub fn wants_vsync(self) -> bool {
        matches!(self, RenderProfile::HardwareVsync)
    }

    pub fn parse(raw: &str) -> Option<Self> {
        match raw.trim().to_ascii_lowercase().as_str() {
            "auto" | "default" => Some(RenderProfile::Auto),
            "hardware" | "accelerated" | "gpu" | "hw" => Some(RenderProfile::Hardware),
            "hardware_vsync" | "hardware-vsync" | "hw_vsync" | "hw-vsync" | "vsync" => {
                Some(RenderProfile::HardwareVsync)
            }
            "software" | "sw" => Some(RenderProfile::Software),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VideoFilter {
    #[default]
    Sharp,
    Smooth,
    Scanlines,
    CrtLite,
    CrtArcade,
    CrtDeluxe,
    CrtShader,
    CrtArcadeShader,
    CrtPvmShader,
    CrtCabinet,
    PvmSharp,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AspectMode {
    #[default]
    Fit,
    Integer,
    Stretch,
}

impl AspectMode {
    pub fn label(self) -> &'static str {
        match self {
            AspectMode::Fit => "FIT",
            AspectMode::Integer => "INTEGER",
            AspectMode::Stretch => "STRETCH",
        }
    }

    pub fn cycle(self, delta: i8) -> Self {
        let all = [AspectMode::Fit, AspectMode::Integer, AspectMode::Stretch];
        let idx = all.iter().position(|v| *v == self).unwrap_or(0) as i8;
        let next = (idx + delta).rem_euclid(all.len() as i8) as usize;
        all[next]
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ScorebarStyle {
    /// Slanted scoreplates with name + win count (original layout).
    Plates,
    /// Just the players' gamertags, pulled in toward the center of the screen.
    #[default]
    Centered,
}

impl ScorebarStyle {
    pub fn label(self) -> &'static str {
        match self {
            ScorebarStyle::Plates => "PLATES",
            ScorebarStyle::Centered => "CENTERED",
        }
    }

    pub fn cycle(self, delta: i8) -> Self {
        let all = [ScorebarStyle::Plates, ScorebarStyle::Centered];
        let idx = all.iter().position(|v| *v == self).unwrap_or(0) as i8;
        let next = (idx + delta).rem_euclid(all.len() as i8) as usize;
        all[next]
    }
}

impl VideoFilter {
    pub fn label(self) -> &'static str {
        match self {
            VideoFilter::Sharp => "SHARP",
            VideoFilter::Smooth => "SMOOTH",
            VideoFilter::Scanlines => "SCANLINES",
            VideoFilter::CrtLite => "CRT LITE",
            VideoFilter::CrtArcade => "CRT ARCADE",
            VideoFilter::CrtDeluxe => "CRT DELUXE",
            VideoFilter::CrtShader => "CRT SHADER",
            VideoFilter::CrtArcadeShader => "CRT ARCADE GL",
            VideoFilter::CrtPvmShader => "CRT PVM GL",
            VideoFilter::CrtCabinet => "CRT CABINET",
            VideoFilter::PvmSharp => "PVM SHARP",
        }
    }

    pub fn cycle(self, delta: i8) -> Self {
        let all = [
            VideoFilter::Sharp,
            VideoFilter::Smooth,
            VideoFilter::Scanlines,
            VideoFilter::CrtLite,
            VideoFilter::CrtArcade,
            VideoFilter::CrtDeluxe,
            VideoFilter::CrtShader,
            VideoFilter::CrtArcadeShader,
            VideoFilter::CrtPvmShader,
            VideoFilter::CrtCabinet,
            VideoFilter::PvmSharp,
        ];
        let idx = all.iter().position(|v| *v == self).unwrap_or(0) as i8;
        let next = (idx + delta).rem_euclid(all.len() as i8) as usize;
        all[next]
    }

    pub fn parse(raw: &str) -> Option<Self> {
        let normalized = raw
            .trim()
            .to_ascii_lowercase()
            .replace('-', "_")
            .replace(' ', "_");
        match normalized.as_str() {
            "sharp" | "nearest" => Some(VideoFilter::Sharp),
            "smooth" | "linear" => Some(VideoFilter::Smooth),
            "scanlines" | "scanline" => Some(VideoFilter::Scanlines),
            "crt_lite" | "lite" => Some(VideoFilter::CrtLite),
            "crt_arcade" | "arcade" => Some(VideoFilter::CrtArcade),
            "crt_deluxe" | "deluxe" => Some(VideoFilter::CrtDeluxe),
            "crt_shader" | "shader" | "glsl" | "fightcade" | "fightcade_crt" => {
                Some(VideoFilter::CrtShader)
            }
            "crt_arcade_gl" | "arcade_gl" | "crt_shader_arcade" | "shader_arcade" => {
                Some(VideoFilter::CrtArcadeShader)
            }
            "crt_pvm_gl" | "pvm_gl" | "crt_shader_pvm" | "shader_pvm" => {
                Some(VideoFilter::CrtPvmShader)
            }
            "crt_cabinet" | "cabinet" => Some(VideoFilter::CrtCabinet),
            "pvm_sharp" | "pvm" => Some(VideoFilter::PvmSharp),
            _ => None,
        }
    }

    pub fn needs_hardware_budget(self) -> bool {
        matches!(
            self,
            VideoFilter::CrtArcade
                | VideoFilter::CrtDeluxe
                | VideoFilter::CrtShader
                | VideoFilter::CrtArcadeShader
                | VideoFilter::CrtPvmShader
                | VideoFilter::CrtCabinet
        )
    }

    pub fn uses_opengl_shader(self) -> bool {
        self.opengl_shader_mode().is_some()
    }

    pub fn opengl_shader_mode(self) -> Option<i32> {
        match self {
            VideoFilter::CrtShader => Some(0),
            VideoFilter::CrtArcadeShader => Some(1),
            VideoFilter::CrtPvmShader => Some(2),
            _ => None,
        }
    }
}

fn default_input_delay() -> u32 {
    3
}

fn default_true() -> bool {
    true
}

fn default_volume_percent() -> u8 {
    100
}

pub fn path() -> PathBuf {
    Path::new(CONFIG_PATH).to_path_buf()
}

pub fn load() -> Config {
    load_dotenv();
    let mut cfg = match std::fs::read_to_string(path()) {
        Ok(s) => match toml::from_str::<Config>(&s) {
            Ok(mut cfg) => {
                println!("Loaded config from {}", path().display());
                migrate_username_confirmation(&s, &mut cfg);
                cfg
            }
            Err(e) => {
                println!("Config parse error ({e}); using defaults");
                Config::default()
            }
        },
        Err(_) => {
            println!("No config at {} — using defaults", path().display());
            Config::default()
        }
    };
    let had_player_username = !cfg.player_username.trim().is_empty();
    apply_env_overrides(&mut cfg);
    cfg.volume_percent = cfg.volume_percent.min(100);
    cfg.input_delay = cfg.input_delay.min(8);
    let mut needs_save = !had_player_username && cfg.player_username_autogenerated;
    if cfg.volume_percent == 0 {
        // Configs written while Config::default() zeroed volume_percent have
        // 0 persisted; nobody chose a silent install, so rescue them to 80.
        cfg.volume_percent = 80;
        needs_save = true;
    }
    if cfg.guest_device_id.is_empty() {
        cfg.guest_device_id = generate_device_id();
        needs_save = true;
    }
    if needs_save {
        save(&cfg);
    }
    cfg
}

/// Generate a random 32-char hex device ID (128-bit) using only stdlib.
/// Called once when config has no device_id; result is immediately persisted.
fn generate_device_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let pid = std::process::id() as u128;
    let sentinel: u64 = 0;
    let stack_addr = &sentinel as *const u64 as u128;
    // Mix entropy sources with FNV-1a
    let mix_a = nanos ^ (pid << 17) ^ (stack_addr >> 3);
    let mix_b = nanos
        .wrapping_add(pid)
        .wrapping_add(stack_addr.wrapping_mul(0x9e37_79b9_7f4a_7c15));
    let mut h1: u64 = 0xcbf29ce484222325;
    for b in mix_a.to_le_bytes() {
        h1 ^= b as u64;
        h1 = h1.wrapping_mul(0x100000001b3);
    }
    let mut h2: u64 = 0x14650fb0739d0383;
    for b in mix_b.to_le_bytes() {
        h2 ^= b as u64;
        h2 = h2.wrapping_mul(0x100000001b3);
    }
    format!("{h1:016x}{h2:016x}")
}

pub fn save(cfg: &Config) {
    match toml::to_string_pretty(cfg) {
        Ok(s) => {
            if let Err(e) = std::fs::write(path(), s) {
                println!("Failed to write config: {e}");
            } else {
                println!("Saved config to {}", path().display());
            }
        }
        Err(e) => println!("Failed to serialize config: {e}"),
    }
}

pub fn env_value(key: &str) -> Option<String> {
    std::env::var(key)
        .ok()
        .filter(|v| !v.trim().is_empty())
        .or_else(|| dotenv_value(key))
}

fn apply_env_overrides(cfg: &mut Config) {
    if let Some(v) = env_value("FREEPLAY_SIGNALING_URL") {
        cfg.signaling_url = v;
    }
    if let Some(v) = env_value("FREEPLAY_DISCORD_CLIENT_ID") {
        cfg.discord_client_id = v;
    }
    if let Some(v) = env_value("FREEPLAY_DISCORD_WEBHOOK_URL") {
        cfg.discord_webhook_url = v;
    }
    if let Some(v) = env_value("FREEPLAY_RENDER_PROFILE").and_then(|v| RenderProfile::parse(&v)) {
        cfg.render_profile = v;
    }
    if let Some(v) = env_value("FREEPLAY_VIDEO_FILTER").and_then(|v| VideoFilter::parse(&v)) {
        cfg.video_filter = v;
    }
    if let Some(v) = env_value("FREEPLAY_STATS_URL") {
        cfg.stats_url = v;
    }
    if cfg.player_username.trim().is_empty() {
        if let Some(username) =
            env_value("FREEPLAY_USERNAME").and_then(|raw| sanitize_username(&raw))
        {
            cfg.player_username = username;
            cfg.player_username_autogenerated = false;
        } else {
            cfg.player_username = default_username();
            cfg.player_username_autogenerated = true;
        }
        cfg.player_username_confirmed = false;
    }
}

fn migrate_username_confirmation(raw_config: &str, cfg: &mut Config) {
    let Ok(value) = toml::from_str::<toml::Value>(raw_config) else {
        return;
    };
    let has_saved_username = value
        .get("player_username")
        .and_then(|v| v.as_str())
        .map(|s| !s.trim().is_empty())
        .unwrap_or(false);
    let has_confirmed_flag = value.get("player_username_confirmed").is_some();
    let has_generated_flag = value.get("player_username_autogenerated").is_some();
    if has_saved_username && !has_confirmed_flag && !has_generated_flag {
        cfg.player_username_confirmed = true;
        cfg.player_username_autogenerated = false;
    }
}

pub fn default_username() -> String {
    let raw = std::env::var("FREEPLAY_USERNAME")
        .ok()
        .unwrap_or_else(crate::wuname::random_username);
    sanitize_username(&raw).unwrap_or_else(|| "Player".into())
}

pub fn sanitize_username(raw: &str) -> Option<String> {
    let mut out = String::new();
    for c in raw.trim().chars() {
        if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
            out.push(c);
        } else if c.is_whitespace() && !out.ends_with('_') {
            out.push('_');
        }
        if out.len() >= MAX_USERNAME_LEN {
            break;
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.len() >= 2 {
        Some(out)
    } else {
        None
    }
}

pub fn normalize_email(raw: &str) -> Option<String> {
    let email = raw.trim().to_ascii_lowercase();
    if email.len() > 254 {
        return None;
    }
    let (local, domain) = email.split_once('@')?;
    if local.is_empty()
        || domain.is_empty()
        || domain.starts_with('.')
        || domain.ends_with('.')
        || !domain.contains('.')
        || email.chars().any(char::is_whitespace)
    {
        return None;
    }
    Some(email)
}

fn load_dotenv() {
    let Some(path) = find_dotenv() else {
        return;
    };
    let Ok(s) = std::fs::read_to_string(&path) else {
        return;
    };
    for line in s.lines().filter_map(parse_env_line) {
        if std::env::var_os(&line.0).is_none() {
            std::env::set_var(line.0, line.1);
        }
    }
}

fn dotenv_value(key: &str) -> Option<String> {
    let path = find_dotenv()?;
    let s = std::fs::read_to_string(&path).ok()?;
    for (k, v) in s.lines().filter_map(parse_env_line) {
        if k == key && !v.trim().is_empty() {
            return Some(v);
        }
    }
    None
}

fn find_dotenv() -> Option<PathBuf> {
    let cwd = PathBuf::from(".env");
    if cwd.exists() {
        return Some(cwd);
    }
    let exe_dir = std::env::current_exe().ok()?.parent()?.to_path_buf();
    let beside_exe = exe_dir.join(".env");
    if beside_exe.exists() {
        return Some(beside_exe);
    }
    None
}

fn parse_env_line(line: &str) -> Option<(String, String)> {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
        return None;
    }
    let (key, value) = line.split_once('=')?;
    let key = key.trim();
    if key.is_empty() {
        return None;
    }
    let value = value
        .trim()
        .trim_matches('"')
        .trim_matches('\'')
        .to_string();
    Some((key.to_string(), value))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_config_matches_serde_defaults() {
        // Config::default() must agree with the serde field defaults; the
        // derived impl used to zero volume_percent, shipping silent installs.
        let cfg = Config::default();
        assert_eq!(cfg.volume_percent, 100);
        assert!(cfg.discord_rpc_enabled);
        assert!(cfg.crt_corner_bend);
        assert_eq!(cfg.render_profile, RenderProfile::Auto);
        assert_eq!(cfg.input_delay, 3);
    }

    #[test]
    fn video_filter_parses_deluxe_aliases() {
        assert_eq!(
            VideoFilter::parse("crt_deluxe"),
            Some(VideoFilter::CrtDeluxe)
        );
        assert_eq!(
            VideoFilter::parse("CRT Deluxe"),
            Some(VideoFilter::CrtDeluxe)
        );
        assert_eq!(
            VideoFilter::parse("fightcade"),
            Some(VideoFilter::CrtShader)
        );
        assert_eq!(
            VideoFilter::parse("crt shader"),
            Some(VideoFilter::CrtShader)
        );
        assert_eq!(
            VideoFilter::parse("crt arcade gl"),
            Some(VideoFilter::CrtArcadeShader)
        );
        assert_eq!(
            VideoFilter::parse("pvm gl"),
            Some(VideoFilter::CrtPvmShader)
        );
    }

    #[test]
    fn migrates_saved_username_as_confirmed() {
        let mut cfg = Config {
            player_username: "OldName".into(),
            ..Config::default()
        };
        migrate_username_confirmation("player_username = \"OldName\"\n", &mut cfg);
        assert!(cfg.player_username_confirmed);
        assert!(!cfg.player_username_autogenerated);
    }

    #[test]
    fn generated_username_flag_is_not_confirmed() {
        let mut cfg = Config::default();
        apply_env_overrides(&mut cfg);
        if !cfg.player_username.is_empty() && cfg.player_username_autogenerated {
            assert!(!cfg.player_username_confirmed);
        }
    }
}
