// Generated by mk2-main/tools/export_freeplay_addresses.py.
// Source: C:/Users/xbx/Workplace/mk2-main/src/mk2.map
// Copy into Freeplay only after rebuilding the ROM and validating netplay.
#![allow(dead_code)]

pub const ACTIVE_PROCESS_LIST_ADDR: usize = 0x1B8DA; // active
pub const FREEZE_TIMER_ADDR: usize = 0x250F4; // f_freeze_timer
pub const FREE_OBJECT_LIST_ADDR: usize = 0x253A4; // ofree
pub const FREE_PROCESS_LIST_ADDR: usize = 0x1B8DE; // free
pub const GROUND_SKEW_FLAG_ADDR: usize = 0x250F8; // f_skew
pub const GSTATE_ADDR: usize = 0x253B8; // gstate
pub const HITBOX_FLAG_ADDR: usize = 0x2577A; // f_colbox
pub const MPROC_TIMER_ADDR: usize = 0x1B8E2; // timer
pub const NETPLAY_SYNC_ADDR: usize = 0x24AA8; // netplay_sync
pub const NO_BLOOD_FLAG_ADDR: usize = 0x256CC; // f_no_blood
pub const NO_VIOLENCE_FLAG_ADDR: usize = 0x256CA; // f_no_violence
pub const OBJECT_LIST_1_ADDR: usize = 0x24E0C; // objlst
pub const OBJECT_LIST_2_ADDR: usize = 0x24E10; // objlst2
pub const OBJECT_LIST_3_ADDR: usize = 0x24E14; // objlst3
pub const OBJECT_LIST_END_ADDR: usize = 0x24E18; // last_objlst
pub const OBJECT_STORE_ADDR: usize = 0x14EE2; // objstr
pub const OVERLOAD_ADDR: usize = 0x1B8E6; // overload
pub const P1_HP_ADDR: usize = 0x253DC; // p1_bar
pub const P1_MATCHW: usize = 0x253E0; // p1_matchw
pub const P1_X_ADDR: usize = 0x253EE; // p1_x, p1_bcq + 0x08
pub const P1_Y_ADDR: usize = 0x253F0; // p1_y, p1_bcq + 0x0A
pub const P2_HP_ADDR: usize = 0x25556; // p2_bar
pub const P2_MATCHW: usize = 0x2555A; // p2_matchw
pub const P2_X_ADDR: usize = 0x25568; // p2_x, p2_bcq + 0x08
pub const P2_Y_ADDR: usize = 0x2556A; // p2_y, p2_bcq + 0x0A
pub const ROUND_NUM: usize = 0x256DE; // round_num
pub const SHADOWS_FLAG_ADDR: usize = 0x250F6; // f_shadows
pub const WINNER_STATUS: usize = 0x256E0; // winner_status

pub const ZERO_TARGETS: &[usize] = &[FREEZE_TIMER_ADDR, HITBOX_FLAG_ADDR, NETPLAY_SYNC_ADDR];
