// Generated by mk2-main/tools/export_freeplay_addresses.py.
// Source: C:/Users/xbx/Workplace/mk2-main/src/mk2.map
// Copy into Freeplay after rebuilding the ROM. Do not edit by hand.
#![allow(dead_code, non_snake_case)]

use std::collections::HashMap;

/// FBNeo maps MK2's system RAM at this offset, so every address here is
/// (TMS34010 bit address / 8) - this base. Anything that follows a POINTER
/// stored in game RAM (process blocks, object blocks) has to apply the same
/// conversion by hand -- the stored value is a raw bit address.
pub const FBNEO_SYSTEM_RAM_BASE: usize = 0x200000;

/// FNV of the mk2.zip `COMPILED` was exported alongside, in the form
/// `matchmaking::rom_fnv_hash` produces. Only consulted for a ROM that
/// carries no address manifest (built before 2026-10-06): such a ROM gets
/// `COMPILED` only if its hash matches. Empty = exported without `--rom`.
pub const SOURCE_ROM_FNV: &str = "3133ed65";

/// `fp_addr_manifest` (mk2-main src/FPADDR.ASM): magic words, then the
/// layout version, a count, and count x (FNV-1a 32 of the name, bit address).
pub const MANIFEST_MAGIC: [u16; 4] = [0xF4E5, 0xA9D1, 0x5046, 0x4441];
pub const MANIFEST_VERSION: u16 = 1;

/// The RAM the client reads and pokes, as FBNeo SYSTEM_RAM offsets.
/// Get the live one with `mk2_addrs::a()`, never `COMPILED` directly.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Addrs {
    pub ACTIVE_PROCESS_LIST_ADDR: usize,
    pub BACKGROUND_LIST_1_ADDR: usize,
    pub BACKGROUND_LIST_2_ADDR: usize,
    pub BACKGROUND_LIST_3_ADDR: usize,
    pub BACKGROUND_LIST_4_ADDR: usize,
    pub BACKGROUND_LIST_5_ADDR: usize,
    pub BACKGROUND_LIST_6_ADDR: usize,
    pub BACKGROUND_LIST_7_ADDR: usize,
    pub BACKGROUND_LIST_8_ADDR: usize,
    pub FREEZE_TIMER_ADDR: usize,
    pub FREE_OBJECT_LIST_ADDR: usize,
    pub FREE_PROCESS_LIST_ADDR: usize,
    pub GROUND_SKEW_FLAG_ADDR: usize,
    pub GSTATE_ADDR: usize,
    pub HITBOX_FLAG_ADDR: usize,
    pub MPROC_TIMER_ADDR: usize,
    pub NETPLAY_ACTIVE_ADDR: usize,
    pub NETPLAY_SYNC_ADDR: usize,
    pub NO_BLOOD_FLAG_ADDR: usize,
    pub NO_VIOLENCE_FLAG_ADDR: usize,
    pub OBJECT_LIST_1_ADDR: usize,
    pub OBJECT_LIST_2_ADDR: usize,
    pub OBJECT_LIST_3_ADDR: usize,
    pub OBJECT_LIST_END_ADDR: usize,
    pub OBJECT_STORE_ADDR: usize,
    pub OVERLOAD_ADDR: usize,
    pub P1_CHAR_ADDR: usize,
    pub P1_HP_ADDR: usize,
    pub P1_MATCHW: usize,
    pub P1_PROC_ADDR: usize,
    pub P1_X_ADDR: usize,
    pub P1_Y_ADDR: usize,
    pub P2_CHAR_ADDR: usize,
    pub P2_HP_ADDR: usize,
    pub P2_MATCHW: usize,
    pub P2_PROC_ADDR: usize,
    pub P2_X_ADDR: usize,
    pub P2_Y_ADDR: usize,
    pub PEAK_OVERLOAD_ADDR: usize,
    pub QDMA_DROPS_ADDR: usize,
    pub ROUND_NUM: usize,
    pub SHADOWS_FLAG_ADDR: usize,
    pub WINNER_STATUS: usize,
}

impl Addrs {
    /// RAM wiped before a netplay session so both peers start equal.
    pub fn zero_targets(&self) -> [usize; 3] {
        [self.FREEZE_TIMER_ADDR, self.HITBOX_FLAG_ADDR, self.NETPLAY_SYNC_ADDR]
    }
}

/// Exported from the map above - right only for the ROM `SOURCE_ROM_FNV` names.
pub const COMPILED: Addrs = Addrs {
    ACTIVE_PROCESS_LIST_ADDR: 0x16F88, // active
    BACKGROUND_LIST_1_ADDR: 0x2086E, // baklst1
    BACKGROUND_LIST_2_ADDR: 0x2086A, // baklst2
    BACKGROUND_LIST_3_ADDR: 0x20866, // baklst3
    BACKGROUND_LIST_4_ADDR: 0x20862, // baklst4
    BACKGROUND_LIST_5_ADDR: 0x2085E, // baklst5
    BACKGROUND_LIST_6_ADDR: 0x2085A, // baklst6
    BACKGROUND_LIST_7_ADDR: 0x20856, // baklst7
    BACKGROUND_LIST_8_ADDR: 0x20852, // baklst8
    FREEZE_TIMER_ADDR: 0x20B96, // f_freeze_timer
    FREE_OBJECT_LIST_ADDR: 0x214BE, // ofree
    FREE_PROCESS_LIST_ADDR: 0x16F8C, // free
    GROUND_SKEW_FLAG_ADDR: 0x20B9A, // f_skew
    GSTATE_ADDR: 0x214D2, // gstate
    HITBOX_FLAG_ADDR: 0x21B58, // f_colbox
    MPROC_TIMER_ADDR: 0x16F90, // timer
    NETPLAY_ACTIVE_ADDR: 0x21B5A, // f_netplay
    NETPLAY_SYNC_ADDR: 0x2046E, // netplay_sync
    NO_BLOOD_FLAG_ADDR: 0x217EE, // f_no_blood
    NO_VIOLENCE_FLAG_ADDR: 0x217EC, // f_no_violence
    OBJECT_LIST_1_ADDR: 0x20872, // objlst
    OBJECT_LIST_2_ADDR: 0x20876, // objlst2
    OBJECT_LIST_3_ADDR: 0x2087A, // objlst3
    OBJECT_LIST_END_ADDR: 0x208BA, // last_objlst
    OBJECT_STORE_ADDR: 0x0E286, // objstr
    OVERLOAD_ADDR: 0x16F94, // overload
    P1_CHAR_ADDR: 0x214E8, // p1_char
    P1_HP_ADDR: 0x214F6, // p1_bar
    P1_MATCHW: 0x214FA, // p1_matchw
    P1_PROC_ADDR: 0x214E4, // p1_proc
    P1_X_ADDR: 0x21508, // p1_x, p1_bcq + 0x08
    P1_Y_ADDR: 0x2150A, // p1_y, p1_bcq + 0x0A
    P2_CHAR_ADDR: 0x21662, // p2_char
    P2_HP_ADDR: 0x21670, // p2_bar
    P2_MATCHW: 0x21674, // p2_matchw
    P2_PROC_ADDR: 0x2165E, // p2_proc
    P2_X_ADDR: 0x21682, // p2_x, p2_bcq + 0x08
    P2_Y_ADDR: 0x21684, // p2_y, p2_bcq + 0x0A
    PEAK_OVERLOAD_ADDR: 0x16FB8, // peak_overload
    QDMA_DROPS_ADDR: 0x16FDA, // qdma_drops
    ROUND_NUM: 0x21808, // round_num
    SHADOWS_FLAG_ADDR: 0x20B98, // f_shadows
    WINNER_STATUS: 0x2180A, // winner_status
};

/// Every entry's manifest name and hash - what `from_manifest` looks up.
pub const MANIFEST_NAMES: &[(&str, u32)] = &[
    ("active", 0xD975992F),
    ("baklst1", 0x9A2F49DF),
    ("baklst2", 0x9B2F4B72),
    ("baklst3", 0x9C2F4D05),
    ("baklst4", 0x952F4200),
    ("baklst5", 0x962F4393),
    ("baklst6", 0x972F4526),
    ("baklst7", 0x982F46B9),
    ("baklst8", 0xA12F54E4),
    ("f_freeze_timer", 0xF75C6BC3),
    ("ofree", 0xD3BA455C),
    ("free", 0x99B3EEDB),
    ("f_skew", 0xFF12BE40),
    ("gstate", 0xA25F855B),
    ("f_colbox", 0x4714E6B1),
    ("timer", 0x5C68ED22),
    ("f_netplay", 0xF73F9D13),
    ("netplay_sync", 0xEFCDEC58),
    ("f_no_blood", 0x4E082CD2),
    ("f_no_violence", 0x945E13E3),
    ("objlst", 0xD76C3955),
    ("objlst2", 0x865E5D25),
    ("objlst3", 0x855E5B92),
    ("last_objlst", 0xD760D0BE),
    ("objstr", 0x61C17F6D),
    ("overload", 0xBA0B8807),
    ("p1_char", 0x4C0BF747),
    ("p1_bar", 0xF0634100),
    ("p1_matchw", 0x6B7D90ED),
    ("p1_proc", 0x7ADABCEF),
    ("p1_x", 0x84AD83C5),
    ("p1_y", 0x83AD8232),
    ("p2_char", 0x14E7A314),
    ("p2_bar", 0x3BEDB52D),
    ("p2_matchw", 0xDDDB740A),
    ("p2_proc", 0xC4E89870),
    ("p2_x", 0x0A252E70),
    ("p2_y", 0x0B253003),
    ("peak_overload", 0xDDCD1E51),
    ("qdma_drops", 0xC5E8E4CF),
    ("round_num", 0x139A168C),
    ("f_shadows", 0xFCC5A5BB),
    ("winner_status", 0x988A8FAD),
];

/// Program-ROM symbols the manifest also carries (bit addresses in ROM,
/// read out of the ROM image, not RAM): `rom_name` is the build stamp.
pub const ROM_POINTERS: &[(&str, u32)] = &[
    ("rom_name", 0x5C4637B9),
];

/// Build the table from a ROM's manifest (name hash -> TMS34010 bit
/// address). Err names the first entry the ROM does not carry.
pub fn from_manifest(m: &HashMap<u32, u32>) -> Result<Addrs, &'static str> {
    let f = |hash: u32, name: &'static str| -> Result<usize, &'static str> {
        let bit = *m.get(&hash).ok_or(name)? as usize;
        if bit % 8 != 0 {
            return Err(name);
        }
        (bit / 8).checked_sub(FBNEO_SYSTEM_RAM_BASE).ok_or(name)
    };
    Ok(Addrs {
        ACTIVE_PROCESS_LIST_ADDR: f(0xD975992F, "active")?,
        BACKGROUND_LIST_1_ADDR: f(0x9A2F49DF, "baklst1")?,
        BACKGROUND_LIST_2_ADDR: f(0x9B2F4B72, "baklst2")?,
        BACKGROUND_LIST_3_ADDR: f(0x9C2F4D05, "baklst3")?,
        BACKGROUND_LIST_4_ADDR: f(0x952F4200, "baklst4")?,
        BACKGROUND_LIST_5_ADDR: f(0x962F4393, "baklst5")?,
        BACKGROUND_LIST_6_ADDR: f(0x972F4526, "baklst6")?,
        BACKGROUND_LIST_7_ADDR: f(0x982F46B9, "baklst7")?,
        BACKGROUND_LIST_8_ADDR: f(0xA12F54E4, "baklst8")?,
        FREEZE_TIMER_ADDR: f(0xF75C6BC3, "f_freeze_timer")?,
        FREE_OBJECT_LIST_ADDR: f(0xD3BA455C, "ofree")?,
        FREE_PROCESS_LIST_ADDR: f(0x99B3EEDB, "free")?,
        GROUND_SKEW_FLAG_ADDR: f(0xFF12BE40, "f_skew")?,
        GSTATE_ADDR: f(0xA25F855B, "gstate")?,
        HITBOX_FLAG_ADDR: f(0x4714E6B1, "f_colbox")?,
        MPROC_TIMER_ADDR: f(0x5C68ED22, "timer")?,
        NETPLAY_ACTIVE_ADDR: f(0xF73F9D13, "f_netplay")?,
        NETPLAY_SYNC_ADDR: f(0xEFCDEC58, "netplay_sync")?,
        NO_BLOOD_FLAG_ADDR: f(0x4E082CD2, "f_no_blood")?,
        NO_VIOLENCE_FLAG_ADDR: f(0x945E13E3, "f_no_violence")?,
        OBJECT_LIST_1_ADDR: f(0xD76C3955, "objlst")?,
        OBJECT_LIST_2_ADDR: f(0x865E5D25, "objlst2")?,
        OBJECT_LIST_3_ADDR: f(0x855E5B92, "objlst3")?,
        OBJECT_LIST_END_ADDR: f(0xD760D0BE, "last_objlst")?,
        OBJECT_STORE_ADDR: f(0x61C17F6D, "objstr")?,
        OVERLOAD_ADDR: f(0xBA0B8807, "overload")?,
        P1_CHAR_ADDR: f(0x4C0BF747, "p1_char")?,
        P1_HP_ADDR: f(0xF0634100, "p1_bar")?,
        P1_MATCHW: f(0x6B7D90ED, "p1_matchw")?,
        P1_PROC_ADDR: f(0x7ADABCEF, "p1_proc")?,
        P1_X_ADDR: f(0x84AD83C5, "p1_x")?,
        P1_Y_ADDR: f(0x83AD8232, "p1_y")?,
        P2_CHAR_ADDR: f(0x14E7A314, "p2_char")?,
        P2_HP_ADDR: f(0x3BEDB52D, "p2_bar")?,
        P2_MATCHW: f(0xDDDB740A, "p2_matchw")?,
        P2_PROC_ADDR: f(0xC4E89870, "p2_proc")?,
        P2_X_ADDR: f(0x0A252E70, "p2_x")?,
        P2_Y_ADDR: f(0x0B253003, "p2_y")?,
        PEAK_OVERLOAD_ADDR: f(0xDDCD1E51, "peak_overload")?,
        QDMA_DROPS_ADDR: f(0xC5E8E4CF, "qdma_drops")?,
        ROUND_NUM: f(0x139A168C, "round_num")?,
        SHADOWS_FLAG_ADDR: f(0xFCC5A5BB, "f_shadows")?,
        WINNER_STATUS: f(0x988A8FAD, "winner_status")?,
    })
}

/// The table for the ROM that is loaded right now.
pub fn a() -> &'static Addrs {
    crate::rom_manifest::current()
}
