// Generated by mk2-main/tools/export_freeplay_addresses.py.
// Source: C:/Users/xbx/Workplace/mk2-main/src/mk2.map
// Copy into Freeplay only after rebuilding the ROM and validating netplay.
#![allow(dead_code)]

pub const ACTIVE_PROCESS_LIST_ADDR: usize = 0x1B8DA; // active
pub const BACKGROUND_LIST_1_ADDR: usize = 0x24EAA; // baklst1
pub const BACKGROUND_LIST_2_ADDR: usize = 0x24EA6; // baklst2
pub const BACKGROUND_LIST_3_ADDR: usize = 0x24EA2; // baklst3
pub const BACKGROUND_LIST_4_ADDR: usize = 0x24E9E; // baklst4
pub const BACKGROUND_LIST_5_ADDR: usize = 0x24E9A; // baklst5
pub const BACKGROUND_LIST_6_ADDR: usize = 0x24E96; // baklst6
pub const BACKGROUND_LIST_7_ADDR: usize = 0x24E92; // baklst7
pub const BACKGROUND_LIST_8_ADDR: usize = 0x24E8E; // baklst8
pub const FREEZE_TIMER_ADDR: usize = 0x25196; // f_freeze_timer
pub const FREE_OBJECT_LIST_ADDR: usize = 0x254E6; // ofree
pub const FREE_PROCESS_LIST_ADDR: usize = 0x1B8DE; // free
pub const GROUND_SKEW_FLAG_ADDR: usize = 0x2519A; // f_skew
pub const GSTATE_ADDR: usize = 0x254FA; // gstate
pub const HITBOX_FLAG_ADDR: usize = 0x258BC; // f_colbox
pub const MPROC_TIMER_ADDR: usize = 0x1B8E2; // timer
pub const NETPLAY_SYNC_ADDR: usize = 0x24AAA; // netplay_sync
pub const NO_BLOOD_FLAG_ADDR: usize = 0x2580E; // f_no_blood
pub const NO_VIOLENCE_FLAG_ADDR: usize = 0x2580C; // f_no_violence
pub const OBJECT_LIST_1_ADDR: usize = 0x24EAE; // objlst
pub const OBJECT_LIST_2_ADDR: usize = 0x24EB2; // objlst2
pub const OBJECT_LIST_3_ADDR: usize = 0x24EB6; // objlst3
pub const OBJECT_LIST_END_ADDR: usize = 0x24EBA; // last_objlst
pub const OBJECT_STORE_ADDR: usize = 0x14EE2; // objstr
pub const OVERLOAD_ADDR: usize = 0x1B8E6; // overload
pub const P1_CHAR_ADDR: usize = 0x25510; // p1_char
pub const P1_HP_ADDR: usize = 0x2551E; // p1_bar
pub const P1_MATCHW: usize = 0x25522; // p1_matchw
pub const P1_X_ADDR: usize = 0x25530; // p1_x, p1_bcq + 0x08
pub const P1_Y_ADDR: usize = 0x25532; // p1_y, p1_bcq + 0x0A
pub const P2_CHAR_ADDR: usize = 0x2568A; // p2_char
pub const P2_HP_ADDR: usize = 0x25698; // p2_bar
pub const P2_MATCHW: usize = 0x2569C; // p2_matchw
pub const P2_X_ADDR: usize = 0x256AA; // p2_x, p2_bcq + 0x08
pub const P2_Y_ADDR: usize = 0x256AC; // p2_y, p2_bcq + 0x0A
pub const ROUND_NUM: usize = 0x25820; // round_num
pub const SHADOWS_FLAG_ADDR: usize = 0x25198; // f_shadows
pub const WINNER_STATUS: usize = 0x25822; // winner_status

pub const ZERO_TARGETS: &[usize] = &[FREEZE_TIMER_ADDR, HITBOX_FLAG_ADDR, NETPLAY_SYNC_ADDR];
