//! Which RAM addresses the loaded `mk2.zip` uses, read out of the ROM itself.
//!
//! Every Lab tool, the trainer pokes and the `f_netplay` write go through
//! `mk2_addrs::a()`, and those addresses move whenever mk2-main's `.bss`
//! grows, which is most rebuilds. A table compiled into the client was right
//! for exactly one ROM; any other build got silently wrong memory, and the
//! hash check that guarded it could only say "no".
//!
//! Since 2026-10-06 the ROM carries its own table: `fp_addr_manifest`
//! (mk2-main `src/FPADDR.ASM`, generated by `tools/export_freeplay_addresses.py`),
//! with every address filled in by the linker. This module pulls the two
//! program chips (uj12 even bytes, ug12 odd) out of the zip, finds the
//! manifest by its magic words, and builds the table from it. So the client
//! works with any build that carries the manifest, however it was zipped.
//!
//! A ROM without one (built before the manifest existed) falls back to
//! `mk2_addrs::COMPILED`, trusted only when its zip hash matches the one that
//! table was exported from - the old behaviour.
//!
//! `current()` does no I/O: it is called on every RAM peek. `refresh()` does
//! the reading, caches by (path, size, mtime), and is called at startup, on
//! Lab entry, before a netplay session and by `mk2_addr_check::check()`.

use std::collections::HashMap;
use std::io::Read;
use std::path::PathBuf;
use std::sync::atomic::{AtomicPtr, Ordering};
use std::sync::Mutex;
use std::time::SystemTime;

use crate::mk2_addrs::{self, Addrs};

/// Where the live table came from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Source {
    /// Read from the ROM's own manifest - right for this ROM by construction.
    Manifest,
    /// No manifest, but the zip is the one `COMPILED` was exported from.
    CompiledByHash,
    /// No manifest and the hash differs: `COMPILED` is in use and is
    /// probably wrong. `found` is the loaded zip's hash.
    CompiledMismatch { found: String },
    /// No manifest and `COMPILED` records no hash - nothing to compare.
    CompiledUnrecorded,
    /// No ROM found or readable.
    NoRom,
}

#[derive(Clone, PartialEq, Eq)]
struct Key {
    path: PathBuf,
    len: u64,
    modified: Option<SystemTime>,
}

struct State {
    key: Option<Key>,
    source: Source,
    /// The ROM's build stamp (`rom_name`), when its manifest points at one.
    stamp: Option<String>,
}

static CURRENT: AtomicPtr<Addrs> = AtomicPtr::new(std::ptr::null_mut());
static STATE: Mutex<State> = Mutex::new(State {
    key: None,
    source: Source::NoRom,
    stamp: None,
});

/// The loaded ROM's build stamp, e.g. "REV 4.0 - PLAYTEST (A71B5*)". None
/// for a ROM without a manifest. No I/O: whatever the last `refresh()` read.
pub fn build_stamp() -> Option<String> {
    STATE.lock().unwrap_or_else(|e| e.into_inner()).stamp.clone()
}

/// The table in use. `COMPILED` until the first `refresh()`.
pub fn current() -> &'static Addrs {
    let p = CURRENT.load(Ordering::Acquire);
    if p.is_null() {
        &mk2_addrs::COMPILED
    } else {
        // SAFETY: only ever set from `Box::leak`, never freed. A table is
        // leaked per distinct ROM file seen, which is a handful per run.
        unsafe { &*p }
    }
}

/// Re-read the ROM if the file changed. Returns the source of the table now
/// in use, and whether the table itself changed.
pub fn refresh() -> (Source, bool) {
    let mut state = STATE.lock().unwrap_or_else(|e| e.into_inner());
    let key = crate::rom::find_rom_zip().and_then(|path| {
        let meta = std::fs::metadata(&path).ok()?;
        Some(Key {
            path,
            len: meta.len(),
            modified: meta.modified().ok(),
        })
    });
    if key.is_some() && key == state.key {
        return (state.source.clone(), false);
    }
    let (table, source, stamp) = match &key {
        None => (mk2_addrs::COMPILED, Source::NoRom, None),
        Some(k) => match std::fs::read(&k.path) {
            Ok(zip) => select(&zip),
            Err(_) => (mk2_addrs::COMPILED, Source::NoRom, None),
        },
    };
    let changed = *current() != table;
    if changed {
        CURRENT.store(Box::leak(Box::new(table)), Ordering::Release);
    }
    let line = match &source {
        Source::Manifest => "address table read from the ROM's manifest".to_string(),
        Source::CompiledByHash => "ROM has no manifest; compiled table matches its hash".into(),
        Source::CompiledMismatch { found } => format!(
            "ROM has no manifest and is {found}, not {} - Lab RAM tools will read the wrong memory",
            mk2_addrs::SOURCE_ROM_FNV
        ),
        Source::CompiledUnrecorded => "ROM has no manifest; compiled table unchecked".into(),
        Source::NoRom => "no ROM readable; compiled address table in use".into(),
    };
    println!("[addr] {line}");
    if let Some(st) = &stamp {
        println!("[addr] ROM build: {st}");
    }
    state.key = key;
    state.source = source.clone();
    state.stamp = stamp;
    (source, changed)
}

fn select(zip: &[u8]) -> (Addrs, Source, Option<String>) {
    let rom = program_rom(zip);
    if let Some(m) = rom.as_deref().and_then(parse_manifest) {
        let stamp = rom.as_deref().and_then(|r| rom_string(r, &m, "rom_name"));
        match mk2_addrs::from_manifest(&m) {
            Ok(t) => return (t, Source::Manifest, stamp),
            Err(missing) => {
                println!("[addr] ROM manifest lacks '{missing}' - falling back to compiled table")
            }
        }
    }
    let expected = mk2_addrs::SOURCE_ROM_FNV.trim();
    if expected.is_empty() {
        return (mk2_addrs::COMPILED, Source::CompiledUnrecorded, None);
    }
    let found = crate::matchmaking::fnv_of(zip);
    if found.eq_ignore_ascii_case(expected) {
        (mk2_addrs::COMPILED, Source::CompiledByHash, None)
    } else {
        (mk2_addrs::COMPILED, Source::CompiledMismatch { found }, None)
    }
}

/// Program ROM starts at this TMS34010 bit address (mk2-main `mk2.cmd`).
const PROGRAM_ROM_BIT_BASE: u32 = 0xFF80_0000;

/// A zero-terminated ASCII string in the program ROM, located through a
/// `mk2_addrs::ROM_POINTERS` entry of the manifest.
fn rom_string(rom: &[u8], m: &HashMap<u32, u32>, name: &str) -> Option<String> {
    let hash = mk2_addrs::ROM_POINTERS.iter().find(|(n, _)| *n == name)?.1;
    let bit = m.get(&hash)?.checked_sub(PROGRAM_ROM_BIT_BASE)?;
    if bit % 8 != 0 {
        return None;
    }
    let at = (bit / 8) as usize;
    let bytes: Vec<u8> = rom.get(at..)?.iter().take(64).take_while(|b| **b != 0).copied().collect();
    let s = String::from_utf8(bytes).ok()?;
    (!s.is_empty() && s.chars().all(|c| c.is_ascii_graphic() || c == ' ')).then_some(s)
}

/// "REV 4.0 - PLAYTEST (A71B5*)" -> "REVISION 4.0 PLAYTEST BUILD (A71B5*)",
/// the line the main screen shows. Anything not in that shape is shown as
/// the ROM wrote it.
pub fn build_label(stamp: &str) -> String {
    let parsed = (|| {
        let rest = stamp.strip_prefix("REV ")?;
        let (rev, rest) = rest.split_once(" - ")?;
        let (kind, id) = rest.split_once(" (")?;
        let id = id.strip_suffix(')')?;
        Some(format!("REVISION {rev} {kind} BUILD ({id})"))
    })();
    parsed.unwrap_or_else(|| stamp.to_string())
}

/// The 1 MB program ROM: uj12 holds the even bytes, ug12 the odd ones.
fn program_rom(zip: &[u8]) -> Option<Vec<u8>> {
    let even = zip_entry(zip, |n| n.contains("uj12"))?;
    let odd = zip_entry(zip, |n| n.contains("ug12"))?;
    if even.len() != odd.len() {
        return None;
    }
    let mut flat = Vec::with_capacity(even.len() * 2);
    for (e, o) in even.iter().zip(odd.iter()) {
        flat.push(*e);
        flat.push(*o);
    }
    Some(flat)
}

/// Name hash -> TMS34010 bit address, or None if the ROM carries no manifest
/// (or one in a layout this client does not know).
fn parse_manifest(rom: &[u8]) -> Option<HashMap<u32, u32>> {
    let magic: Vec<u8> = mk2_addrs::MANIFEST_MAGIC
        .iter()
        .flat_map(|w| w.to_le_bytes())
        .collect();
    let at = (0..rom.len().saturating_sub(magic.len()))
        .step_by(2)
        .find(|&i| rom[i..i + magic.len()] == magic[..])?;
    let word = |i: usize| -> Option<u16> {
        Some(u16::from_le_bytes([*rom.get(i)?, *rom.get(i + 1)?]))
    };
    let long = |i: usize| -> Option<u32> {
        Some(u32::from(word(i)?) | (u32::from(word(i + 2)?) << 16))
    };
    let mut p = at + magic.len();
    if word(p)? != mk2_addrs::MANIFEST_VERSION {
        println!("[addr] ROM manifest is layout {}, client reads {}", word(p)?, mk2_addrs::MANIFEST_VERSION);
        return None;
    }
    let count = usize::from(word(p + 2)?);
    p += 4;
    let mut m = HashMap::with_capacity(count);
    for k in 0..count {
        m.insert(long(p + 8 * k)?, long(p + 8 * k + 4)?);
    }
    Some(m)
}

/// The uncompressed bytes of the first entry whose lower-cased name matches.
/// Stored and deflated entries only - all a ROM zip ever uses.
fn zip_entry(zip: &[u8], want: impl Fn(&str) -> bool) -> Option<Vec<u8>> {
    let u16_at = |i: usize| -> Option<usize> {
        Some(usize::from(u16::from_le_bytes([*zip.get(i)?, *zip.get(i + 1)?])))
    };
    let u32_at = |i: usize| -> Option<usize> {
        let b = zip.get(i..i + 4)?;
        Some(u32::from_le_bytes([b[0], b[1], b[2], b[3]]) as usize)
    };
    // End of central directory: last occurrence of its signature.
    let eocd = (0..zip.len().saturating_sub(21))
        .rev()
        .find(|&i| zip[i..i + 4] == [0x50, 0x4b, 0x05, 0x06])?;
    let entries = u16_at(eocd + 10)?;
    let mut p = u32_at(eocd + 16)?;
    for _ in 0..entries {
        if zip.get(p..p + 4)? != [0x50, 0x4b, 0x01, 0x02] {
            return None;
        }
        let method = u16_at(p + 10)?;
        let csize = u32_at(p + 20)?;
        let usize_ = u32_at(p + 24)?;
        let nlen = u16_at(p + 28)?;
        let elen = u16_at(p + 30)?;
        let clen = u16_at(p + 32)?;
        let local = u32_at(p + 42)?;
        let name = String::from_utf8_lossy(zip.get(p + 46..p + 46 + nlen)?).to_lowercase();
        p += 46 + nlen + elen + clen;
        if !want(&name) {
            continue;
        }
        if zip.get(local..local + 4)? != [0x50, 0x4b, 0x03, 0x04] {
            return None;
        }
        let data = local + 30 + u16_at(local + 26)? + u16_at(local + 28)?;
        let raw = zip.get(data..data + csize)?;
        return match method {
            0 => Some(raw.to_vec()),
            8 => {
                let mut out = Vec::with_capacity(usize_);
                flate2::read::DeflateDecoder::new(raw).read_to_end(&mut out).ok()?;
                Some(out)
            }
            _ => None,
        };
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A program ROM carrying a manifest built the way GSPA lays it out.
    fn rom_with(entries: &[(u32, u32)]) -> Vec<u8> {
        let mut rom = vec![0xFFu8; 64];
        for w in mk2_addrs::MANIFEST_MAGIC {
            rom.extend(w.to_le_bytes());
        }
        rom.extend(mk2_addrs::MANIFEST_VERSION.to_le_bytes());
        rom.extend((entries.len() as u16).to_le_bytes());
        for (h, a) in entries {
            rom.extend(((h & 0xFFFF) as u16).to_le_bytes());
            rom.extend(((h >> 16) as u16).to_le_bytes());
            rom.extend(((a & 0xFFFF) as u16).to_le_bytes());
            rom.extend(((a >> 16) as u16).to_le_bytes());
        }
        rom
    }

    #[test]
    fn a_full_manifest_builds_the_table() {
        // Every entry at a distinct, byte-aligned address above the RAM base.
        let entries: Vec<(u32, u32)> = mk2_addrs::MANIFEST_NAMES
            .iter()
            .enumerate()
            .map(|(i, (_, h))| (*h, 0x0100_0000 + (i as u32) * 0x10))
            .collect();
        let m = parse_manifest(&rom_with(&entries)).expect("manifest found");
        let t = mk2_addrs::from_manifest(&m).expect("table built");
        assert_eq!(t.zero_targets().len(), 3);
        // 0x01000000 bits = 0x200000 bytes = RAM base, so offsets start at 0.
        assert!([t.GSTATE_ADDR, t.P1_X_ADDR, t.NETPLAY_ACTIVE_ADDR]
            .iter()
            .all(|&a| a < 0x1000));
    }

    #[test]
    fn a_missing_entry_is_named() {
        let m = parse_manifest(&rom_with(&[(1, 0x0100_0000)])).expect("manifest found");
        assert!(mk2_addrs::from_manifest(&m).is_err());
    }

    #[test]
    fn the_stamp_reads_as_a_revision_line() {
        assert_eq!(
            build_label("REV 4.0 - PLAYTEST (A71B5*)"),
            "REVISION 4.0 PLAYTEST BUILD (A71B5*)"
        );
        assert_eq!(build_label("SOMETHING ELSE"), "SOMETHING ELSE");
    }

    #[test]
    fn no_magic_means_no_manifest() {
        assert!(parse_manifest(&[0xFF; 4096]).is_none());
    }
}
